### ISSUE TITLE
Support for 0.9.4

### ISSUE THREAD

**Issue by wlstyy** [Yelp/pyleus#104]
Storm has a long term issue https://issues.apache.org/jira/browse/STORM-130
This issue can cause storm halt there. We can only restart the supervisor when this issue happened.
This issue is fixed in 0.9.4. So we want pyleus to support 0.9.4.

**Comment by poros** [comment]
AFAIK, Storm 0.9.4 hasn't been released yet (last time I checked they were still discussing and voting).

**Comment by wlstyy** [comment]
Just released.
https://github.com/apache/storm/releases/tag/v0.9.4

**Comment by poros** [comment]
Ack

**Comment by dearli** [comment]
We expect new pyleus version which supports storm 0.9..4.Is there any time line?Thanks

**Comment by poros** [comment]
We are actively working on it. The release is due soon. See #126
