### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by hadisotudeh** [Yelp/pyleus#115]
Hi
I get the following error, any idea?
Error:
pyleus local DRC.jar 
  
File "/home/hadi/Storm/apache-storm-0.9.2-incubating/bin/storm", line 71
    print "******************************************"
                                                     ^
SyntaxError: Missing parentheses in call to 'print'
pyleus local: error: [StormError] Storm command failed. Run with --verbose for more info.

**Comment by poros** [comment]
Whatever the error is, you can't print from a topology component with Pyleus. It's written in the docs http://yelp.github.io/pyleus/logging.html?highlight=print

**Comment by moandcompany** [comment]
Using `print` statements in your topologies will blow up your application at runtime, as Storm uses `STDIN` and `STDOUT` for communication between tasks. Take a look at using Python's logging capabilities to help with debugging.
