### ISSUE TITLE
Ambiguity in documentation

### ISSUE THREAD

**Issue by johanneshk** [Yelp/pyleus#116]
Written [here](http://yelp.github.io/pyleus/yaml.html?highlight=tasks): "tasks(int): Number of tasks per executor."
And [here](http://yelp.github.io/pyleus/parallelism.html?highlight=tasks): "You can set the number of tasks per component (NOT per executors) via tasks."
I assume the latter is correct.

**Comment by poros** [comment]
Uh, nice catch! Would you mind submitting a super-quick patch?

**Comment by johanneshk** [comment]
Sure thing, see #117 for the patch.
