### ISSUE TITLE
Free platforms to deploy

### ISSUE THREAD

**Issue by hadisotudeh** [Yelp/pyleus#118]
Hi,
I want to know is there any platforms like Openshift for deployment?

**Comment by poros** [comment]
No one I am aware of, honestly.
There is something related like https://github.com/nathanmarz/storm-deploy, but I've never tried it.

**Comment by hadisotudeh** [comment]
yes, that is for Amazon and I don't know if there is any free plan or not?

**Comment by poros** [comment]
I don't really know, sorry. However, this topic is more suited for the Storm mailing list than the Pyleus project. You may want to ask there as well.
