### ISSUE TITLE
acked and failed tuples in the storm UI

### ISSUE THREAD

**Issue by hadisotudeh** [Yelp/pyleus#121]
Hi
I've submitted my project to the storm cluster and the project is running now but the number of acked and failed tuples are zero!!! in the storm UI.
Should I write some code in ack method?
What should I do in order to get the results in to storm UI?

**Comment by poros** [comment]
Well, it really depends on your topology. SimpleBolt automatically acks tuples, so if you are inheriting from it, you should be fine at the bolt-wise. Spout are very dependent on the source of your data, so if you want to leverage Storm reliability features you need to implement ack and fail methods yourself.

This is the doc page: http://yelp.github.io/pyleus/reliability.html
