### ISSUE TITLE
doc error: pyleus submit [-n NIMBUS_HOST] [-p NIMBUS_PORT] /path/to/pyleus_topology.yaml

### ISSUE THREAD

**Issue by stallman-cui** [Yelp/pyleus#139]
Submit a topology to a Storm cluster:
pyleus submit [-n NIMBUS_HOST] [-p NIMBUS_PORT] /path/to/pyleus_topology.yaml

Here is an error: not pyleus_topology.yaml, it should be a jar, please correct it

**Comment by poros** [comment]
You're right. We are going to update it soon.
