### ISSUE TITLE
can not found redis when build yaml.But i had install redis-py

### ISSUE THREAD

**Issue by fcfangcc** [Yelp/pyleus#144]
[root@nimbus script]# pyleus build storm-2/pyleus_topology.yaml 
pyleus build: error: [VirtualenvError] Failed to execute Python module: handle_topology.handle_Bolt2. Error: Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/tmp/tmpadkG6K/resources/handle_topology/handle_Bolt2.py", line 3, in <module>
    from redis import *
ImportError: No module named redis

But i had install redis ,and in python-shell i can import redis..

install redis by pip.

what should i do?thanks

@poros  if you need ,i can Provide SSH address.you can ssh machine to see the problem

virtualenv ：13.1.2
pyleus：0.3.0
storm：0.9.3
centos：6.6
jdk：1.7
python：2.6.6

**Comment by poros** [comment]
you should specify redis in your `requirements.txt`. See http://yelp.github.io/pyleus/tutorial.html#organize-your-files

**Comment by fcfangcc** [comment]
thanks.
my english is not good,so i did't see it. - . -
