### ISSUE TITLE
How to use other's information stream of kafka on my Bolt?

### ISSUE THREAD

**Issue by BlueKarl** [Yelp/pyleus#146]
Someone use kafka(java) to publish information stream, can I use these message on my bolt(python)  directly？if not，how to do this? If you can reply to me I would be very grateful.....

**Comment by poros** [comment]
I'm not entirely sure you this what your question is about, but we have an example about how to use the kafka spout shipped with Storm at https://github.com/Yelp/pyleus/blob/develop/examples/kafka_spout/pyleus_topology.yaml. The example is not complete, thus not runnable, but it should be of some help.

**Comment by BlueKarl** [comment]
thank you for your help, but i have seen this .  can you give me an example for kafka's spout?

**Comment by BlueKarl** [comment]
look at this,when I use kafka and pyleus,  I'm not sure that it's right to instead common spout:


test_spout(Spout):
     OUTPUT_FIELDS = ['sentence', 'name']
     zookeeper = KazooClient("budget32.rm.ne1.yahoo.com:2181")
     zookeeper.start()
     cluster = Cluster(zookeeper)
     topic = cluster.topics['demo']
     consumer = topic.subscribe('group-name')
     impression = 0
    
     def next_tuple(self):
           for message in consumer:
                 self.emit(("123", "spout"))

if __name__ == "__main__":
    test_spout().run()

**Comment by BlueKarl** [comment]
waiting for your reply, I'm appreciate that you can give me an example for this....

**Comment by BlueKarl** [comment]
hello, i see your example again, for this yaml, should I write a spout.py?  what about "zk_root: /pyleus-kafka-offsets/kafka_spout_example"?I can't understand it

**Comment by poros** [comment]
You don't need to write any spout yourself, if you use those configurations, the Kafka spout already available in Storm is going to be used. You just need to hook it up to your bolts.

The zk_root option let you specify the path in zookeeper your consumer offsets are going to be saved into. Basically, you should change it to something that uniquely identify your spout (like BlueKarlTopologyNumberOne).

You can find more info in the Storm documentation: https://github.com/apache/storm/blob/master/external/storm-kafka/README.md#kafkaconfig

**Comment by BlueKarl** [comment]
Mmmm......        maybe i understand it .  I will try.  if I have problem, I'll leave message for you. thank you for your help

**Comment by poros** [comment]
Ok, closing the issue for now, then. Feel free to reopen it if you have more questions
