### ISSUE TITLE
A plurality of bolt inherit the same bolt

### ISSUE THREAD

**Issue by BlueKarl** [Yelp/pyleus#150]
Excuse me，how to achieve this function（A plurality of bolt inherit the same bolt）？

**Comment by BlueKarl** [comment]
I have a stream like this:
20150807  ip  play  
           .
           .
           .
20150807  ip  sleep
           .
           . 
           .
20150807  ip  happy
           .
           .
           .

I want to separate by play/sleep/happy to different bolt.How to do this?

**Comment by poros** [comment]
I guess you're talking about field grouping... Have you already tried that out?

**Comment by BlueKarl** [comment]
maybe you are right,but i don't know how to achieve what I talk about。 I need  that like：
20150807 ip play            （play＋1）
20150807 ip sleep          （sleep＝1）
20150807 ip sleep          （sleep＝2）
20150807 ip play            （play＝2）
20150807 ip happy           （happy ＝3）
count play/sleep/happy occurrences.....

Could you give me an example of it?

**Comment by BlueKarl** [comment]
and i have a problem:
$ pyleus build pyleus_topology.yaml
pyleus build: error: [VirtualenvError] Failed to execute Python module: QOStest.alluser_count. Error: Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/var/folders/rl/8bkfntmj6lz_9m85jrf5sqgm0000gn/T/tmpSXsFsR/resources/QOStest/alluser_count.py", line 6, in <module>
    from QOStest.sqlconnect.sqlconnect import conn
  File "QOStest/sqlconnect/sqlconnect.py", line 1, in <module>
    from sqlalchemy import *
ImportError: No module named sqlalchemy

but i'm sure i install sqlalchemy....

**Comment by BlueKarl** [comment]
$ pip install sqlalchemy
You are using pip version 7.0.3, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy in /Users/Karl/.virtualenvs/storm/lib/python2.7/site-packages

I install sqlalchemy in my virtualenvs, I use this virtualenvs for my pyleus build, but it isn't work

**Comment by BlueKarl** [comment]
and  how to save the data in mysql?

**Comment by BlueKarl** [comment]
thanks, It's worked now!
