### ISSUE TITLE
Running .jar automatic generated file

### ISSUE THREAD

**Issue by BlueKarl** [Yelp/pyleus#157]
when I running my xxxxx.jar（pyleus local -d xxxxx.jar）
It  auto generared files like this(UUID)：
14cd1e4d-2923-4268-9801-b27f1ec7314f
b3757590-e2f6-4142-bd12-52196b42f939
in /tmp file 

can I choose the other paths to save this？

**Comment by poros** [comment]
Nope, you can't, afaik. That is Storm's doing, Pyleus shouldn't be related. You could try asking on the Storm users mailing list, though.
