### ISSUE TITLE
Kafka spout workers

### ISSUE THREAD

**Issue by jayadevanm** [Yelp/pyleus#177]
I am using the default kafka spout as part of the topology. If I set the workers to three will Pyleus ensue that different workers don't read the same message? Can I be sure I won't end up processing the same message more than once?

**Comment by poros** [comment]
Even if Storm has support for exactly-once semantic (using Trident), Pyleus doesn't offer it out of the box. I guess you'll need to implement this logic yourself, if possible...

**Comment by jayadevanm** [comment]
OK. I tried more than one worker and ended up with more records in the target table than the messages I published to kafka. I was just confirming that I did not miss something. Thanks for the clarification.
