### ISSUE TITLE
Add debug option to pyleus submit subcommand

### ISSUE THREAD

**Issue by victorpoluceno** [Yelp/pyleus#88]
Should be possible to submit a topology to a storm cluster with debug mode on.

**Comment by poros** [comment]
Quoting Storm documentation:

> __TOPOLOGY_DEBUG__ (set with setDebug), when set to true, tells Storm to log every message every emitted by a component. This is useful in local mode when testing topologies, but you probably want to keep this turned off when running topologies on the cluster.

However, I can see the point in making this option at least available to users. Feel free to submit a pull request, if this is a blocking issue for you. Thanks in advance for contributing.

**Comment by victorpoluceno** [comment]
Ok. I'm gonna give it a try a make a PR. Thanks!
