### ISSUE TITLE
Add support for multilang heartbeats

### ISSUE THREAD

**Issue by dan-blanchard** [Yelp/pyleus#9]
apache/storm#286 isn't merged into Storm yet, but when it is, pyleus will need to support it.

**Comment by mzbyszynski** [comment]
+1

**Comment by hellp** [comment]
When will this be released? I tried to build the current develop branch myself (including upping the dependency to storm to 0.9.3 in pom.xml), but running the exclamation topology locally the java process stalls with "backtype.storm.spout.ShellSpout - Start checking heartbeat..." as the last output :(

**Comment by poros** [comment]
I'd like to have a fix also for #10 and to thoroughly test pyleus with Storm 0.9.3 before. Unfortunately, the bandwidth I can allocate to pyleus these days is kinda low... :(

**Comment by poros** [comment]
Closed by #97
