### ISSUE TITLE
Unable to import numpy

### ISSUE THREAD

**Issue by sidthekidder** [Yelp/pyleus#92]
I'm getting the error `ImportError : no module named numpy` when using numpy while building the topology. Does pyleus not support third-party modules.? (same problem is with `requests` module)

**Comment by mzbyszynski** [comment]
Hi @sidthekidder, Did you include them in your `requirements.txt` file?

**Comment by sidthekidder** [comment]
Hadn't seen that config.! Thanks for pointing it out :)
